version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: college_erp_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres.tzahxmdwxfgxfmwnaznd:Aklank2026!Password@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
      - SECRET_KEY=aklank_erp_super_secret_jwt_key_2026_enterprise_v10
      - ENVIRONMENT=production
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: college_erp_redis
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: college_erp_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
